apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: NotIn
      values:
        - m6g.16xlarge
        - m6gd.16xlarge
        - r6g.16xlarge
        - r6gd.16xlarge
        - c6g.16xlarge

  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: "eks-karpenter-tfm"
    securityGroupSelector:
      karpenter.sh/discovery: "eks-karpenter-tfm"
    tags:
      karpenter.sh/discovery: "eks-karpenter-tfm"
  ttlSecondsAfterEmpty: 30
