apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    karpenter.sh/discovery: "eks-karpenter-tfm"
  tags:
    karpenter.sh/discovery: "eks-karpenter-tfm"
